version: 2
updates:
  - commit-message:
      prefix: "Changelog:All"
    directory: /
    package-ecosystem: gomod
    schedule:
      interval: weekly
    reviewers:
      - "mendersoftware/backend-dependabot-reviewers"
  - commit-message:
      prefix: "Changelog:All"
    directory: /
    package-ecosystem: docker
    schedule:
      interval: weekly
    reviewers:
      - "mendersoftware/backend-dependabot-reviewers"
